development:
  life_share_database_username: username
  life_share_database_password: password

test:
  life_share_database_username: username
  life_share_database_password: password

production:
  my_project_database_username: <%= ENV['LIFE_SHARE_DATABASE_USERNAME'] %>
  my_project_database_password: <%= ENV['LIFE_SHARE_DATABASE_PASSWORD'] %>